# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_constituency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=10)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Constituency')),
            ],
            options={
                'verbose_name_plural': 'Work List',
            },
        ),
    ]
