# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='aginst_id',
            new_name='against_id',
        ),
    ]
